 const members = [
    { 
        id:1,
        name:"dawit",
        email:"devo@gmail.com",
        status:"active"
    },
    { 
        id:2,
        name:"kal",
        email:"kal@gmail.com",
        status:"active"
    },
    { 
        id:3,
        name:"nahom",
        email:"nahom@gmail.com",
        status:"inactive"
    },
];
module.exports=members
